
import { AppConfig, Product, User, Post } from "../types";

export const generateWebArchive = (
  config: AppConfig,
  products: Product[],
  users: User[],
  posts: Post[]
): string => {
  const date = new Date().toLocaleDateString();
  
  const styles = `
    body { font-family: 'Helvetica', 'Arial', sans-serif; background: #f5f5f5; color: #333; margin: 0; padding: 40px; }
    .header { background: #000; color: #f4d300; padding: 40px; text-align: center; border-radius: 20px 20px 0 0; }
    .container { max-width: 1000px; margin: 0 auto; background: white; border-radius: 20px; box-shadow: 0 10px 25px rgba(0,0,0,0.1); overflow: hidden; }
    h1 { margin: 0; font-size: 2.5em; letter-spacing: -1px; }
    h2 { border-bottom: 3px solid #f4d300; padding-bottom: 15px; margin-top: 40px; margin-bottom: 20px; font-size: 1.5em; }
    table { width: 100%; border-collapse: collapse; margin-top: 15px; }
    th { background: #f9f9f9; text-align: left; padding: 15px; font-size: 12px; text-transform: uppercase; letter-spacing: 1px; color: #888; }
    td { padding: 15px; border-bottom: 1px solid #eee; font-size: 14px; vertical-align: top; }
    img.thumb { width: 60px; height: 60px; object-fit: cover; border-radius: 8px; background: #eee; }
    .section { padding: 0 40px 40px 40px; }
    .badge { padding: 5px 10px; border-radius: 6px; font-size: 10px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.5px; }
    .badge-green { background: #dcfce7; color: #166534; }
    .badge-red { background: #fee2e2; color: #991b1b; }
    .post-card { display: flex; gap: 20px; margin-bottom: 20px; padding-bottom: 20px; border-bottom: 1px solid #f0f0f0; }
    .post-img { width: 120px; height: 120px; object-fit: cover; border-radius: 12px; }
    .footer { text-align: center; padding: 20px; color: #888; font-size: 12px; border-top: 1px solid #eee; }
  `;

  const productsHtml = products.map(p => `
    <tr>
      <td width="80"><img src="${p.image}" class="thumb" onerror="this.style.display='none'"/></td>
      <td><strong>${p.name}</strong><br/><span style="color:#888; font-size:12px;">${p.category}</span></td>
      <td>${p.description}</td>
      <td style="font-weight:bold;">R${p.price} / ${p.unit}</td>
      <td>${p.available ? '<span class="badge badge-green">Stocked</span>' : '<span class="badge badge-red">Sold Out</span>'}</td>
    </tr>
  `).join('');

  const usersHtml = users.map(u => `
    <tr>
      <td><strong>${u.name}</strong></td>
      <td>${u.email}</td>
      <td>${u.phone}</td>
      <td><span style="color:#f4d300; font-weight:bold; background:black; padding:2px 6px; border-radius:4px;">${u.loyaltyPoints}</span></td>
      <td>${u.role}</td>
    </tr>
  `).join('');

  const postsHtml = posts.map(p => `
    <div class="post-card">
      <img src="${p.imageUrl}" class="post-img" onerror="this.style.display='none'" />
      <div>
        <h4 style="margin: 0 0 10px 0;">${new Date(p.timestamp).toLocaleDateString()}</h4>
        <p style="margin: 0; line-height: 1.6; color: #555;">${p.caption}</p>
      </div>
    </div>
  `).join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Meat Depot Data Backup - ${date}</title>
      <style>${styles}</style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>Meat Depot Archive</h1>
          <p style="margin-top:10px; opacity:0.8;">Generated on ${new Date().toLocaleString()}</p>
        </div>
        
        <div class="section">
          <h2>Inventory Catalog (${products.length})</h2>
          <table>
            <thead><tr><th>Image</th><th>Item</th><th>Description</th><th>Price</th><th>Status</th></tr></thead>
            <tbody>${productsHtml}</tbody>
          </table>
        </div>

        <div class="section">
          <h2>News Feed (${posts.length})</h2>
          ${postsHtml}
        </div>

        <div class="section">
          <h2>Customer Database (${users.length})</h2>
          <table>
            <thead><tr><th>Name</th><th>Email</th><th>Phone</th><th>Pts</th><th>Role</th></tr></thead>
            <tbody>${usersHtml}</tbody>
          </table>
        </div>

        <div class="footer">
          Generated by Meat Depot App Manager. Upload this file to your website server to view online.
        </div>
      </div>
    </body>
    </html>
  `;
};
